#
# Copyright (c) 2006-2007 rPath, Inc.  All Rights Reserved.
#
TOPDIR = ../..
extra_dist = Makefile
dist_files = *.py

all: default-all
dist: $(dist_files) default-dist

clean: default-clean

include $(TOPDIR)/Make.rules
include $(TOPDIR)/Make.defs

# vim: set sts=8 sw=8 noexpandtab :
