#!/usr/bin/python
#
# Copyright (c) 2008 rPath, Inc.  All rights reserved.
#

import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])
if 'RMAKE_PATH' in os.environ:
    sys.path.insert(0, os.environ['RMAKE_PATH'])

from rmake.lib import gencert

if __name__ == "__main__":
    sys.exit(gencert.main(sys.argv[1:]))
