#!/usr/bin/python
#
# Copyright (c) 2006-2007 rPath, Inc.  All rights reserved.
#

import os
import sys



if __name__ == "__main__":
    #if '--debug-all' not in sys.argv:
    #    from conary.lib import importer
    #    importer.install()
    from rmake.cmdline import main
    sys.exit(main.main(sys.argv))
