#!/usr/bin/python
#
# Copyright (c) 2010 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.rpath.com/permanent/licenses/CPL-1.0.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])
if 'RMAKE_PATH' in os.environ:
    sys.path.insert(0, os.environ['RMAKE_PATH'])

# We have to do this early because various Twisted and wokkel modules
# inadvertently cause the default select reactor to be installed.
from twisted.internet import epollreactor
epollreactor.install()

from rmake.core import daemon

if __name__ == "__main__":
    sys.exit(daemon.main())
