#!/bin/sh
#
# Copyright (c) 2006 rPath, Inc.
#
# This program is distributed under the terms of the Common Public License,
# version 1.0. A copy of this license should have been distributed with this
# source file in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/cpl.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the Common Public License for
# full details.
#

bindir=$(dirname $0)
bin=$(basename $0)
importdir=$(cd $bindir/.. 2> /dev/null && pwd -P;)
export PYTHONPATH=$importdir:$CONARY_PATH
config=

if [ "$bin" = "rmake-server" ]; then
    modes=$(stat -c '%a %u %g' $importdir/commands/chroothelper)
    if [ "$modes" != "4755 0 0" ]; then
        echo "run make test to make chroothelper setuid root"
        exit 1;
    else
        config="chrootHelperPath $importdir/commands/chroothelper"
    fi
fi
exec $importdir/commands/$bin "$@" ${config:+--config "${config}"}
