#!/usr/bin/python
#
# Copyright (c) 2006-2007 rPath, Inc.  All rights reserved.
#

import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])
if 'RMAKE_PATH' in os.environ:
    sys.path.insert(0, os.environ['RMAKE_PATH'])

from rmake.server import daemon

if __name__ == "__main__":
    sys.exit(daemon.main(sys.argv))
