#!/bin/sh
#
# Copyright (c) 2006-2007 rPath, Inc.  All rights reserved.
#

bindir=$(dirname $0)
bin=$(basename $0)
importdir=$(cd $bindir/.. 2> /dev/null && pwd -P;)
export PYTHONPATH=$importdir:$CONARY_PATH:$PYTHONPATH
declare -a config
config=

if [ "$bin" = "rmake-server" ]; then
    # single-node local rmake server
    certfile=/tmp/rmake-server-cert.pem
    # Force the generation of a new SSL certificate
    rm -f $certfile
    config=("--config=sslCertPath $certfile"
            )

elif [ "$bin" = "rmake-node" ]; then
    # multi-node rmake worker
    config=("--config=pluginOption build helperDir $importdir/commands"
            )
fi

exec $importdir/commands/$bin "$@" ${config:+"${config[@]}"}
