#!/bin/sh
#
# Copyright (c) 2006-2007 rPath, Inc.  All rights reserved.
#

bindir=$(dirname $0)
bin=$(basename $0)
importdir=$(cd $bindir/.. 2> /dev/null && pwd -P;)
export PYTHONPATH=$importdir:$CONARY_PATH
config=

if [ "$bin" = "rmake-server" ]; then
    modes=$(stat -c '%a %u %g' $importdir/commands/chroothelper)
    if [ "$modes" != "4755 0 0" ]; then
        echo "run make test to make chroothelper setuid root"
        exit 1;
    fi
    certfile=/tmp/rmake-server-cert.pem
    # Force the generation of a new SSL certificate
    rm -f $certfile
    # Using arrays now
    declare -a config
    config=("--config=helperDir $importdir/commands"
            "--config=sslCertPath $certfile")
fi
exec $importdir/commands/$bin "$@" ${config:+"${config[@]}"}
