#!/usr/bin/python
#
# Copyright (c) SAS Institute Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])
if 'RMAKE_PATH' in os.environ:
    sys.path.insert(0, os.environ['RMAKE_PATH'])

# We have to do this early because various Twisted and wokkel modules
# inadvertently cause the default select reactor to be installed.
from twisted.internet import epollreactor
epollreactor.install()

import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

from rmake.core import daemon

if __name__ == "__main__":
    sys.exit(daemon.main())
