#!/usr/bin/python
#
# Copyright (c) rPath, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])
if 'RMAKE_PATH' in os.environ:
    sys.path.insert(0, os.environ['RMAKE_PATH'])

# We have to do this early because various Twisted and wokkel modules
# inadvertently cause the default select reactor to be installed.
from twisted.internet import epollreactor
epollreactor.install()

import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

from rmake.core import daemon

if __name__ == "__main__":
    sys.exit(daemon.main())
