#!/usr/bin/python2.4
#
# Copyright (c) 2006-2007 rPath, Inc.  All rights reserved.
#

import os
import sys

if 'CONARY_PATH' in os.environ:
    sys.path.insert(0, os.environ['CONARY_PATH'])

DEBUG = True

if DEBUG and sys.argv[1] != '--in-term':
    os.execv('/usr/bin/gnome-terminal', ['/usr/bin/gnome-terminal', '-x', sys.argv[0], '--in-term', sys.argv[1]])
else:
    del sys.argv[1]

from rmake.cmdline import xmlcommand

if __name__ == "__main__":
    sys.exit(xmlcommand.main(sys.argv))
